### PR TITLE
[castai-hibernate] feat/hibernate cm state

### PR DESCRIPTION
**Pull request by anthonyvg9**
Add cm state to helm chart for new v0.9 app updates. 

Updated helm and app versions.

### CODE REVIEW

**Review by AugustinasS — CHANGES_REQUESTED** [review]
can you change to v0.10 version

**Review by ronakforcast — APPROVED** [review]
reviwed

**Review by ronakforcast — COMMENTED** [review]
reviewed

**Review by ronakforcast — APPROVED** [review]
looks good

**Pull request closed without merging**
